// <auto-generated />
namespace JobOffers.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updateJobAndApplicationUserTables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateJobAndApplicationUserTables));
        
        string IMigrationMetadata.Id
        {
            get { return "201904032200290_updateJobAndApplicationUserTables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
